### ISSUE TITLE
Allow direct navigation to sub-pages.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia.github.io#29]
Go to oppia.github.io and click on "Reference: Parameters". You get taken to a page called 'http://oppia.github.io/Parameters'.

Now, copy the URL and paste it into another browser tab. You end up at a 404 page.

Instead, the Parameters page should be loaded.

/cc @amgowano @MAKOSCAFEE

**Comment by makoscafee** [comment]
Hi @seanlip  Actually this is cause by `$locationProvider.html5Mode(true);`  which removes `#` in the urls. 
It  re-writes url without `#` in the client side but not in the server side. So when you reload or copy and paste, server does not recorgise that new url try add # before or after / and it will work. Solution which are provided for this does not always work, take a look [here(FAQ)](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode) . We have  implemented all solutions provided except using `.htaccess` which I am not sure if it plays well with GitHub pages servers. 
So we have two options which is to rollback from using  `$locationProvider.html5Mode(true);` and leave all url with `#` . Or write  `.htaccess`

**Comment by seanlip** [comment]
Thanks for checking! According to [this page](https://help.github.com/articles/redirects-on-github-pages/) the second solution is not allowed, so I would lean towards the first one.

**Comment by makoscafee** [comment]
I have sent a PR to fix using first solution.
Thanks.
