### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Shubham-kumar799** [oppia/oppia.github.io#49]
With python 3 the SimpleHTTPServer is merged into http.server. It would be nice to add commands that will get the application work in python 3 as well.

**Comment by Shubham-kumar799** [comment]
#50 - You can review the changes here

**Comment by shitesh2607** [comment]
I want to work on this issue.

**Comment by shitesh2607** [comment]
@Shubham-kumar799 
I would like to work on this issue.

**Comment by BenHenning** [comment]
This was fixed in #51. Thanks for filing this @Shubham-kumar799!
