### ISSUE TITLE
Some Changes in Look of the website 

### ISSUE THREAD

**Issue by aditi5050** [oppia/oppia.github.io#60]
# The name Oppia should be in the center to grab attention  and secondly the GitHub button is too bright and does match the oppia's background color These are the changes suggested by ME , shall look forward with  them and raise a PR .
![preview](https://user-images.githubusercontent.com/102579070/196025150-7e3c37a7-b079-440c-a117-51128c4d0112.jpg)
![oppia_pr_1](https://user-images.githubusercontent.com/102579070/196025154-d390c2e1-4c08-43af-8c59-406e0afbbdbe.jpg)

**Comment by seanlip** [comment]
Please don't raise a PR for this. We aren't going to change this.

**Comment by aditi5050** [comment]
I'll not raise a PR for this but I also wanted to know if there are any issues or tasks that I can work on.

**Comment by seanlip** [comment]
Please follow our [getting started instructions](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up), they will point you in the right direction. Thanks!
